name: pr
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]
  workflow_call:
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}
jobs:
  lint-title:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      # nosemgrep
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6
        env:
          GITHUB_TOKEN: ${{ github.token }}
  label:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # nosemgrep
      - uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6
  label-size:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # nosemgrep
      - uses: pascalgn/size-label-action@56b489b027932ec0cf60438a1a5f1a19c8fc71ff # v0.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
          IGNORED: |
            package-lock.json
            *.lock
            docs/**
